### ISSUE TITLE
Ordering is not preserved for data prop with string keys

### ISSUE THREAD

**Issue by flahertyb** [FormidableLabs/victory-bar#66]
When passing something like this:

![image](https://cloud.githubusercontent.com/assets/1581371/11823296/45efaa36-a341-11e5-87c4-d3414306fb6f.png)

as props, without specifying categories, the library seems to sort the x string values alphabetically, copy the values over to an `xName` property, and assign 1-based index x values to them ( so December gets 1, November gets 2, etc). 

Funny enough, in this instance with Sep Oct Nov Dec, alphabetical ordering reverses the array!

No big deal to specify string x axis ordering elsewhere, but from glancing at the source it seems like the order is supposed to be preserved https://github.com/FormidableLabs/victory-bar/blob/master/src/components/victory-bar.jsx#L292

**Comment by boygirl** [comment]
Hi @flahertyb,  

Sorry for the slow reply. So about this whole alphabetizing thing... Right now specifying categories preserves the order, but specifying data doesn't. This is because when this component is used with the chart wrapper, multiple sources of data are aggregated, and we then have to define axes and non-numeric data ordering based on all of the data. From within chart, there is no way to guarantee that non-numeric input data order is maintained, so we end up alphabetizing it there so that the ordering is predictable. We do the same thing here for consistency. Specifying `tickValues` for an axis within chart will ensure that non-numeric data will take a particular order. 

hope that all made sense! I'll go improve the dos now :smiley:

**Comment by flahertyb** [comment]
@boygirl Realized I never said thanks for getting back to me - so thanks!

**Comment by boygirl** [comment]
@flahertyb you're most welcome! I hope victory is working out for you :)
