### ISSUE TITLE
Is there a prop to specify in number of pixels the space between each bar

### ISSUE THREAD

**Issue by stephenotalora** [FormidableLabs/victory-bar#99]
The domain appears to have control over the width between the bars, is there a more declarative way to specify the spacing and lock it to a specific number?

**Comment by boygirl** [comment]
@stephenotalora you can specify a padding via the style prop like: 
```
style={{
  data: {padding: 10}
}}
```
and that should change the spacing between bars in a group of bars. For non-grouped bars, the domain / scale _does_ control the spacing between the bars so that they will be appropriately placed on the axis.

p.s. you should check out our gitter channel. https://gitter.im/FormidableLabs/victory If  I'm around I'd be happy to help / answer questions
